export const peepOptions = {
  accessories: [
    'Eyepatch',
    'GlassRoundThick',
    'SunglassClubmaster',
    'SunglassWayfarer',
    'GlassAviator',
    'GlassButterfly',
    'GlassButterflyOutline',
    'GlassClubmaster',
    'GlassRound',
    'None',
  ],
  bodies: [
    'BlazerBlackTee',
    'Shirt',
    'ButtonShirt',
    'Dress',
    'Gaming',
    'Geek',
    'Hoodie',
    'PointingUp',
    'Selena',
    'Thunder',
    'Turtleneck',
    'ArmsCrossed',
    'Coffee',
    'Device',
    'DotJacket',
    'Explaining',
    'FurJacket',
    'Killer',
    'Paper',
    'PocketShirt',
    'PoloSweater',
    'ShirtCoat',
    'ShirtFilled',
    'SportyShirt',
    'StripedShirt',
    'Sweater',
    'SweaterDots',
    'Whatever',
    'BlazerBW',
    'BlazerPantsBW',
    'BlazerPantsWB',
    'BlazerWB',
    'CrossedArmsBW',
    'CrossedArmsWB',
    'EasingBW',
    'EasingWB',
    'PointingFingerBW',
    'PointingFingerWB',
    'PolkaDots',
    'RestingBW',
    'RestingWB',
    'RoboDanceBW',
    'RoboDanceOutline',
    'RoboDanceWB',
    'ShirtBW',
    'ShirtPantsBW',
    'ShirtPantsWB',
    'ShirtWB',
    'WalkingBW',
    'WalkingFilled',
    'WalkingWB',
    'Doc',
    'DocProtectiveClothe',
    'DocStethoscope',
    'Bike',
    'ClosedLegBW',
    'ClosedLegWB',
    'CrossedLegs',
    'HandsBackBW',
    'HandsBackWB',
    'MediumBW',
    'MediumWB',
    'OneLegUpBW',
    'OneLegUpWB',
    'WheelChair',
  ],
  faces: [
    'Angry',
    'Blank',
    'Calm',
    'Cheeky',
    'Concerned',
    'Contempt',
    'Cute',
    'Driven',
    'EatingHappy',
    'EyesClosed',
    'OldAged',
    'Serious',
    'Smile',
    'Solemn',
    'Suspicious',
    'Tired',
    'VeryAngry',
    'Awe',
    'ConcernedFear',
    'Cyclops',
    'Explaining',
    'Fear',
    'Hectic',
    'LoveGrin',
    'LoveGrinTeeth',
    'Monster',
    'Rage',
    'SmileBig',
    'SmileLol',
    'SmileTeeth',
    'CalmNM',
    'SmileNM',
    'CheersNM',
  ],
  hair: [
    'Afro',
    'Bald',
    'BaldSides',
    'BaldTop',
    'Bangs',
    'BangsFilled',
    'Bear',
    'Bun',
    'BunCurly',
    'Buns',
    'FlatTop',
    'FlatTopLong',
    'HatHip',
    'Long',
    'LongAfro',
    'LongBangs',
    'LongCurly',
    'Medium',
    'MediumBangs',
    'MediumBangsFilled',
    'MediumLong',
    'MediumShort',
    'MediumStraight',
    'Mohawk',
    'MohawkDino',
    'Pomp',
    'ShavedRight',
    'ShavedSides',
    'ShavedWavy',
    'Short',
    'ShortCurly',
    'ShortMessy',
    'ShortScratch',
    'ShortVolumed',
    'ShortWavy',
    'BantuKnots',
    'Beanie',
    'BunFancy',
    'CornRows',
    'CornRowsFilled',
    'GrayBun',
    'GrayMedium',
    'GrayShort',
    'Hijab',
    'MediumShade',
    'Turban',
    'Twists',
    'TwistsVolumed',
    'DocBouffant',
    'DocSurgery',
    'DocShield',
  ],
  facialHair: [
    'None',
    'Chin',
    'Full',
    'FullMajestic',
    'FullMedium',
    'Goatee',
    'GoateeCircle',
    'Dali',
    'Handlebars',
    'Imperial',
    'Painters',
    'PaintersFilled',
    'Swashbuckler',
    'MoustacheThin',
    'Yosemite',
    'GrayFull',
    'MajesticHandlebars',
  ],
  gradientBackgrounds: [
    { from: '#FF9B9B', to: '#F3D34A' },
    { from: '#95E1D3', to: '#AA96DA' },
    { from: '#A8D8EA', to: '#FCBAD3' },
    { from: '#FFFFD2', to: '#A8E6CF' },
    { from: '#FFB6B9', to: '#E7E6E1' },
    { from: '#F3D34A', to: '#FF9B9B' },
    { from: '#AA96DA', to: '#95E1D3' },
    { from: '#FCBAD3', to: '#A8D8EA' },
    { from: '#A8E6CF', to: '#FFFFD2' },
    { from: '#E7E6E1', to: '#FFB6B9' },
    { from: '#FFD1DC', to: '#87CEEB' },
    { from: '#98FB98', to: '#DDA0DD' },
    { from: '#F0E68C', to: '#87CEFA' },
    { from: '#FFA07A', to: '#98FB98' },
    { from: '#E6E6FA', to: '#FFB6C1' },
    { from: '#B0E0E6', to: '#FFE4B5' },
    { from: '#D8BFD8', to: '#90EE90' },
    { from: '#F08080', to: '#E0FFFF' },
    { from: '#FFDAB9', to: '#B0C4DE' },
    { from: '#DEB887', to: '#98FF98' },
  ],
  solidBackgrounds: [
    '#FF9B9B',
    '#95E1D3',
    '#A8D8EA',
    '#FFFFD2',
    '#FFB6B9',
    '#F3D34A',
    '#AA96DA',
    '#FCBAD3',
    '#A8E6CF',
    '#E7E6E1',
    '#FFB6C1',
    '#98FB98',
    '#87CEEB',
    '#DDA0DD',
    '#F0E68C',
    '#FFA07A',
    '#E6E6FA',
    '#B0E0E6',
    '#D8BFD8',
    '#FFDAB9',
  ],
};
